### PR TITLE
Option to write test results to a file as JSON

### LINKED ISSUE #53: logging summary of testcases
Hello again,

Is there a way to log to a file (JSON preferably)?
We need a summary of the test case results (along with the new timers) logged to a file in order to be visualized by another service.
It could be a very simple JSON with a 
key: testresult and the value: [PASS] GET Latest Testresult (0.02 seconds)
it would be much nice if it was in lists though:

```
[
	{
		"case_name": "Get all",
		"verdict": "fail",
		"time": "0.50"
	},
	{
		"case_name": "Post testresult",
		"verdict": "pass",
		"time": "0.06"
	}
]
```

### PR DESCRIPTION
**Pull request by aviaviavi**
closes #53

### CODE REVIEW

**Comment by aviaviavi** [comment]
@Rashadse let me know what you think

**Comment by Rashadse** [comment]
nice!
for some reason the time elapsed for each case says wrong values like 18 or 15 and so on, it should be 0.1 and 0.2 etc like you did in the time feature. is this a bug?

**Comment by aviaviavi** [comment]
Oh good catch. Internally, elapsed time is tracked in milliseconds, I forgot to have the conversion in there. Will change

**Comment by aviaviavi** [comment]
cc @Rashadse

**Comment by Rashadse** [comment]
Hello again, 
the latest fix shows the correct number but in the wrong form, we are getting 1.0e-2 instead of the simplified form

**Comment by aviaviavi** [comment]
Interestingly, I actually can't seem to reproduce this. Is this happening reliably? What system are you on?

**Comment by Rashadse** [comment]
I am on ubuntu

**Comment by aviaviavi** [comment]
Still can't reproduce, but try again and let me know if that helped

**Comment by Rashadse** [comment]
what we are getting is the scientific notation of the time "elapsedTimeSeconds": 4.6e-2
this is actually fine for us
i think we got what we wanted
you can go ahead and merge the commit

**Comment by aviaviavi** [comment]
Weird, I tried this out on ubuntu and I still can't seem to get it to spit out scientific notation. If this works for you I'll merge for now. We can circle back to it if needed.

**Pull request merged**
