### PR TITLE
Update to LTS 13.13

### PR DESCRIPTION
**Pull request by johnchildren**
Megaparsec 7 is a bit faster and has some error message improvements.
This isn't really justification enough, but this should enable this
package to build in nixpkgs.

The new Header type in http-conduit has also been used over the one
exported by http-types allowing the http-types dependency to be removed.

### CODE REVIEW

**Comment by johnchildren** [comment]
I'm guessing this would potentially justify a new release as well.

**Comment by aviaviavi** [comment]
HI @johnchildren, this is excellent thanks for submitting! Definitely a desirable change and deserves a release. I should have time to review/merge/release in the next few days.

**Comment by johnchildren** [comment]
Ah have actually tried using this and it doesn't work properly, it's making too much white-space when there is a mismatch between the expected response data. Will investigate and hopefully patch.

**Comment by aviaviavi** [comment]
Got it. I'm fine using a different pretty printing library if that easily fixes things. We just need *a* pretty printer because spotting a small difference in a large JSON response is a pretty terrible experience without one.

Let me know if you need any help getting that working again

**Comment by johnchildren** [comment]
Okay. To be clear I don't think it's an issue with the library necessarily,
just seems to be a strange issue with the output. Might be a few different
things at work.

The output of the logger in verbose mode is fine, for example, so perhaps
something to do with printf and the ANSI codes?

Anyway still investigating slowly.

**Comment by johnchildren** [comment]
So looking into this further it seems to be to do with the changes from `2.1.0.1` to `2.2.0.0` of `pretty-simple`, adding this extra-deps section to `stack.yaml` prevents the regression: 

```yaml
extra-deps:
  - pretty-simple-2.1.0.1
```

I don't think this is really a good solution, but I could add it until I can figure out why this is happening and try to submit a fix. It may also be possible that the next major version of [`pretty-simple`](https://github.com/cdepillabout/pretty-simple/blob/master/CHANGELOG.md#next-major-version-bump) might contain the changes needed.

**Comment by aviaviavi** [comment]
Thanks for the investigation here John. I think I'm ok with this sort of extra-dependency addition if that's the only simple fix without a lot of extra work. Just so I understand this fully, would you mind  pasting in some example "ugly" output you're seeing?

**Comment by johnchildren** [comment]
Sorry! Including this would have been helpful earlier!

Without the extra-deps:

```
[PASS] Bar
[FAIL] Foo

Assertion failed: [ Foo ] Incorrect status code from http://${ HOST }/api/v1/foo.
[ 31mExpected:
[ 0m 200.
[ 31mActual:[ 0m 400 ] ]
        ]
    ]

Some tests failed
```

With:

```
[PASS] Bar
[FAIL] Foo

Assertion failed: [Foo] Incorrect status code from http://${HOST}/api/v1/foo. Expected: 200. Actual: 400
```

Now that I'm writing this I'm noticing that there's a bit of extra white-space even around the test names and the environment variables, which I guess might be related?

Anyway I'll push the extra deps to this branch in the meantime.

**Comment by aviaviavi** [comment]
Huh yeah that is odd. Ok well yeah I agree this extra-dep isn't ideal but I think it's worth it to have the megaparsec upgrade. I'll have time to test myself and merge on Friday.

**Comment by aviaviavi** [comment]
This looks great, thanks @johnchildren!

**Pull request merged**
